
server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/product_db
    username: root
    password: ${MYSQL_ROOT_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    producer:
      bootstrap-servers: 0.0.0.0:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.ecommerce.productservice: DEBUG
